stages:
  - build
  - quality

build:
  image: node:latest
  stage: build
  script:
    - echo "Building the project..."

test: 
  image: node:latest
  stage: quality
  script:
    - echo "testing the project..."