image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

build:
  stage: build
  script:
    - docker build -t paulo/projeto-cicd:latest .

push:
  stage: push
  script:
    - docker push paulo/projeto-cicd:latest .|